In [1]:
import numpy as np

In [2]:
#defin matrix A 
# 4 3 2 1
# 3 1 4 2

A = np.array([[4,3,2,1],[3,1,4,2]])
print(A)

#defin matrix B
# 4 3 2
# 3 1 5
# 1 4 7
# 5 2 6
# 3 4 2

B = np.array([[4,3,2],[3,1,5],[1,4,7],[5,2,6],[3,4,2]])
print(B)

[[4 3 2 1]
 [3 1 4 2]]
[[4 3 2]
 [3 1 5]
 [1 4 7]
 [5 2 6]
 [3 4 2]]


In [3]:
#SVD decomposition of A
Ua, sa, VTa = np.linalg.svd(A)
#cast U and VT to matrix
Ua = np.matrix(Ua)
VTa = np.matrix(VTa)
#cast sa to diagonal matrix
sa = np.diag(sa)
#print all matrices
print("U of A")
print(Ua)
print("S of A")
print(sa)
print("VT of A")
print(VTa)

#check if U and VT are orthogonal
if np.allclose(Ua.T, Ua.I):
    print("U of A is orthogonal")
else:
    print("U of A is not orthogonal")
if np.allclose(VTa, VTa.T.I):
    print("VT of A is orthogonal")
else:
    print("VT of A is not orthogonal")




#SVD decomposition of B
Ub, sb, VTb = np.linalg.svd(B)
#cast U and VT to matrix
Ub = np.matrix(Ub)
VTb = np.matrix(VTb)
#cast sa to diagonal matrix
sb = np.diag(sb)
#print all matrices
print("U of B")
print(Ub)
print("S of B")
print(sb)
print("VT of B")
print(VTb)



#check if U and VT are orthogonal
if np.allclose(Ub.T, Ub.I):
    print("U of B is orthogonal")
else:
    print("U of B is not orthogonal")
if np.allclose(VTb, VTb.T.I):
    print("VT of B is orthogonal")
else:
    print("VT of B is not orthogonal")



U of A
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
S of A
[[7.41619849 0.        ]
 [0.         2.23606798]]
VT of A
[[ 0.66742381  0.38138504  0.57207755  0.28603878]
 [-0.31622777 -0.63245553  0.63245553  0.31622777]
 [-0.60302269  0.60302269  0.44120908 -0.27939546]
 [-0.30151134  0.30151134 -0.27939546  0.86030227]]
U of A is orthogonal
VT of A is orthogonal
U of B
[[-0.34257033  0.58307731  0.09625668 -0.38316715 -0.62175881]
 [-0.4064537  -0.17291495 -0.44522011 -0.66625951  0.40345153]
 [-0.53578801 -0.63122898  0.51385337  0.01149083 -0.22428522]
 [-0.56226218  0.0866505  -0.52728265  0.62645945 -0.07664528]
 [-0.33798434  0.47345849  0.50044123  0.12921969  0.62806408]]
S of B
[[13.98490244  0.          0.        ]
 [ 0.          4.18231663  0.        ]
 [ 0.          0.          3.30616567]]
VT of B
[[-0.49701415 -0.43287956 -0.75205866]
 [ 0.72590472  0.26744412 -0.63366867]
 [-0.47543588  0.86086522 -0.1813058 ]]
U of B is orthogonal
VT of B is orthogonal


In [4]:
#SVD decomposition of A economy size
Uae, sae, VTae = np.linalg.svd(A, full_matrices=False)
#cast U and VT to matrix
Uae = np.matrix(Uae)
VTae = np.matrix(VTae)
#cast sa to diagonal matrix
sae = np.diag(sae)
#print Uae, sae, VTae
print("U of A economy size")
print(Uae)
print("VT of A economy size")
print(VTae)

#SVD decomposition of B economy size   
Ube, sbe, VTbe = np.linalg.svd(B, full_matrices=False)
#cast U and VT to matrix
Ube = np.matrix(Ube)
VTbe = np.matrix(VTbe)
#cast sa to diagonal matrix
sbe = np.diag(sbe)
#print Ube, sbe, VTbe
print("U of B economy size")
print(Ube)
print("VT of B economy size")
print(VTbe)


U of A economy size
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
VT of A economy size
[[ 0.66742381  0.38138504  0.57207755  0.28603878]
 [-0.31622777 -0.63245553  0.63245553  0.31622777]]
U of B economy size
[[-0.34257033  0.58307731  0.09625668]
 [-0.4064537  -0.17291495 -0.44522011]
 [-0.53578801 -0.63122898  0.51385337]
 [-0.56226218  0.0866505  -0.52728265]
 [-0.33798434  0.47345849  0.50044123]]
VT of B economy size
[[-0.49701415 -0.43287956 -0.75205866]
 [ 0.72590472  0.26744412 -0.63366867]
 [-0.47543588  0.86086522 -0.1813058 ]]


In [5]:
#calculate the rank of A
rankA = np.linalg.matrix_rank(A)
print("rank of A")
print(rankA)




rank of A
2


In [6]:
from sklearn.decomposition import TruncatedSVD
#calculate the truncated SVD of A

def rank(rank, matrix):
    svd = TruncatedSVD(rank)
    svd.fit(matrix)
    matrix_transformed = svd.transform(matrix)
    return matrix_transformed


print("lower approximation of A rank 1")
print(rank(1,A))
print("lower approximation of A rank 2")
print(rank(2,A))

print("lower approximation of B rank 1")
print(rank(1,B))
print("lower approximation of B rank 2")
print(rank(2,B))



lower approximation of A rank 1
[[5.24404424]
 [5.24404424]]
lower approximation of A rank 2
[[ 5.24404424 -1.58113883]
 [ 5.24404424  1.58113883]]
lower approximation of B rank 1
[[4.79081258]
 [5.68421529]
 [7.49294299]
 [7.8631818 ]
 [4.72667799]]
lower approximation of B rank 2
[[ 4.79081258 -2.43861391]
 [ 5.68421529  0.72318506]
 [ 7.49294299  2.63999946]
 [ 7.8631818  -0.36239983]
 [ 4.72667799 -1.98015332]]


In [7]:
#calculate the l1, l2, l_inf,frobenius,nuclear norm of A
def norms(matrix,name):
    l1 = np.linalg.norm(matrix, ord=1)
    l2 = np.linalg.norm(matrix, ord=2)
    l_inf = np.linalg.norm(matrix, ord=np.inf)
    frobenius = np.linalg.norm(matrix, ord='fro')
    nuclear = np.linalg.norm(matrix, ord='nuc')
    print("l1 norm of Matrix " + name)
    print(l1)
    print("l2 norm of Matrix " + name)
    print(l2)
    print("l_inf norm of Matrix " + name)
    print(l_inf)
    print("frobenius norm of Matrix " + name)
    print(frobenius)
    print("nuclear norm of Matrix " + name)
    print(nuclear)

norms(A,"A")
norms(B,"B")




l1 norm of Matrix A
7.0
l2 norm of Matrix A
7.416198487095664
l_inf norm of Matrix A
10.0
frobenius norm of Matrix A
7.745966692414834
nuclear norm of Matrix A
9.652266464595453
l1 norm of Matrix B
22.0
l2 norm of Matrix B
13.984902437006962
l_inf norm of Matrix B
13.0
frobenius norm of Matrix B
14.966629547095765
nuclear norm of Matrix B
21.47338473715689


In [8]:
    #calculate the condition number of A
    def cond(matrix):
        return  np.linalg.cond(matrix)

    print("condition number of A")
    print(cond(A))
    print("condition number of B")
    print(cond(B))

condition number of A
3.3166247903554003
condition number of B
4.229946052622944
